// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAGFPKiPrz_iaD_u7eeRs0RKGm3LUPrcW8',
    appId: '1:720112448735:web:735634ec8c851a02c7a56a',
    messagingSenderId: '720112448735',
    projectId: 'bitirme1453',
    authDomain: 'bitirme1453.firebaseapp.com',
    storageBucket: 'bitirme1453.appspot.com',
    measurementId: 'G-H5PFZN14FP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBjzXkd80XsaeQdQd1yHRQB9nKeWq8-Joc',
    appId: '1:720112448735:android:1f51e85e21a0ec54c7a56a',
    messagingSenderId: '720112448735',
    projectId: 'bitirme1453',
    storageBucket: 'bitirme1453.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_tyIZWNp1Njs-60pxGM1c814e8eJcJ74',
    appId: '1:720112448735:ios:c717d8c0b5bd6264c7a56a',
    messagingSenderId: '720112448735',
    projectId: 'bitirme1453',
    storageBucket: 'bitirme1453.appspot.com',
    iosClientId: '720112448735-45fkbuvorv7tfqvl4vpoc0o81cbqe4iq.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterIlkProje',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA_tyIZWNp1Njs-60pxGM1c814e8eJcJ74',
    appId: '1:720112448735:ios:c717d8c0b5bd6264c7a56a',
    messagingSenderId: '720112448735',
    projectId: 'bitirme1453',
    storageBucket: 'bitirme1453.appspot.com',
    iosClientId: '720112448735-45fkbuvorv7tfqvl4vpoc0o81cbqe4iq.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterIlkProje',
  );
}
